//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RomStationRebase.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RomStationRebase.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à All games.
        /// </summary>
        public static string AllGames {
            get {
                return ResourceManager.GetString("AllGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Check all.
        /// </summary>
        public static string CheckAll {
            get {
                return ResourceManager.GetString("CheckAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Database synced.
        /// </summary>
        public static string DbSynced {
            get {
                return ResourceManager.GetString("DbSynced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Deselect.
        /// </summary>
        public static string Deselect {
            get {
                return ResourceManager.GetString("Deselect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Last sync:.
        /// </summary>
        public static string LastSync {
            get {
                return ResourceManager.GetString("LastSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rebase to….
        /// </summary>
        public static string RebaseTo {
            get {
                return ResourceManager.GetString("RebaseTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Search a game….
        /// </summary>
        public static string SearchPlaceholder {
            get {
                return ResourceManager.GetString("SearchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select all.
        /// </summary>
        public static string SelectAll {
            get {
                return ResourceManager.GetString("SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} games selected.
        /// </summary>
        public static string SelectedCount {
            get {
                return ResourceManager.GetString("SelectedCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sync DB.
        /// </summary>
        public static string SyncDb {
            get {
                return ResourceManager.GetString("SyncDb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à SYSTEMS.
        /// </summary>
        public static string Systems {
            get {
                return ResourceManager.GetString("Systems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Uncheck all.
        /// </summary>
        public static string UncheckAll {
            get {
                return ResourceManager.GetString("UncheckAll", resourceCulture);
            }
        }

        public static string Splash_LoadingConfig {
            get { return ResourceManager.GetString("Splash_LoadingConfig", resourceCulture); }
        }

        public static string Splash_DetectingRS {
            get { return ResourceManager.GetString("Splash_DetectingRS", resourceCulture); }
        }

        public static string Splash_ReadingConfig {
            get { return ResourceManager.GetString("Splash_ReadingConfig", resourceCulture); }
        }

        public static string Splash_CheckingDB {
            get { return ResourceManager.GetString("Splash_CheckingDB", resourceCulture); }
        }

        public static string Splash_CopyingDB {
            get { return ResourceManager.GetString("Splash_CopyingDB", resourceCulture); }
        }

        public static string Splash_VerifyingDB {
            get { return ResourceManager.GetString("Splash_VerifyingDB", resourceCulture); }
        }

        public static string Splash_Starting {
            get { return ResourceManager.GetString("Splash_Starting", resourceCulture); }
        }

        public static string Splash_LoadingLibrary {
            get { return ResourceManager.GetString("Splash_LoadingLibrary", resourceCulture); }
        }

        public static string Splash_RSFound {
            get { return ResourceManager.GetString("Splash_RSFound", resourceCulture); }
        }

        public static string Splash_RSOpen {
            get { return ResourceManager.GetString("Splash_RSOpen", resourceCulture); }
        }

        public static string Splash_DBCorrupted {
            get { return ResourceManager.GetString("Splash_DBCorrupted", resourceCulture); }
        }

        public static string Splash_ConfigCorrupted_State {
            get { return ResourceManager.GetString("Splash_ConfigCorrupted_State", resourceCulture); }
        }

        public static string Splash_ConfigCorrupted_Prefs {
            get { return ResourceManager.GetString("Splash_ConfigCorrupted_Prefs", resourceCulture); }
        }

        public static string Issues_FilterLabel {
            get { return ResourceManager.GetString("Issues_FilterLabel", resourceCulture); }
        }

        public static string Badge_FilesMissing {
            get { return ResourceManager.GetString("Badge_FilesMissing", resourceCulture); }
        }

        public static string Badge_CoverMissing {
            get { return ResourceManager.GetString("Badge_CoverMissing", resourceCulture); }
        }

        public static string Badge_MultiDisc {
            get { return ResourceManager.GetString("Badge_MultiDisc", resourceCulture); }
        }

        public static string Splash_DBLocked {
            get { return ResourceManager.GetString("Splash_DBLocked", resourceCulture); }
        }

        public static string Column_Title {
            get { return ResourceManager.GetString("Column_Title", resourceCulture); }
        }

        public static string Column_System {
            get { return ResourceManager.GetString("Column_System", resourceCulture); }
        }

        public static string Column_Files {
            get { return ResourceManager.GetString("Column_Files", resourceCulture); }
        }

        public static string Column_Issues {
            get { return ResourceManager.GetString("Column_Issues", resourceCulture); }
        }

        public static string Badge_SingleFile {
            get { return ResourceManager.GetString("Badge_SingleFile", resourceCulture); }
        }

        public static string Rebase_Title {
            get { return ResourceManager.GetString("Rebase_Title", resourceCulture); }
        }
        public static string Rebase_TargetPath {
            get { return ResourceManager.GetString("Rebase_TargetPath", resourceCulture); }
        }
        public static string Rebase_Browse {
            get { return ResourceManager.GetString("Rebase_Browse", resourceCulture); }
        }
        public static string Rebase_Architecture {
            get { return ResourceManager.GetString("Rebase_Architecture", resourceCulture); }
        }
        public static string Rebase_GenerateM3U {
            get { return ResourceManager.GetString("Rebase_GenerateM3U", resourceCulture); }
        }
        public static string Rebase_DuplicatePolicy {
            get { return ResourceManager.GetString("Rebase_DuplicatePolicy", resourceCulture); }
        }
        public static string Rebase_DuplicatePolicy_Ignore {
            get { return ResourceManager.GetString("Rebase_DuplicatePolicy_Ignore", resourceCulture); }
        }
        public static string Rebase_DuplicatePolicy_Overwrite {
            get { return ResourceManager.GetString("Rebase_DuplicatePolicy_Overwrite", resourceCulture); }
        }
        public static string Rebase_ParallelCopies {
            get { return ResourceManager.GetString("Rebase_ParallelCopies", resourceCulture); }
        }
        public static string Rebase_Start {
            get { return ResourceManager.GetString("Rebase_Start", resourceCulture); }
        }
        public static string Rebase_Pause {
            get { return ResourceManager.GetString("Rebase_Pause", resourceCulture); }
        }
        public static string Rebase_Resume {
            get { return ResourceManager.GetString("Rebase_Resume", resourceCulture); }
        }
        public static string Rebase_Cancel {
            get { return ResourceManager.GetString("Rebase_Cancel", resourceCulture); }
        }
        public static string Rebase_OpenFolder {
            get { return ResourceManager.GetString("Rebase_OpenFolder", resourceCulture); }
        }
        public static string Rebase_ExportLog {
            get { return ResourceManager.GetString("Rebase_ExportLog", resourceCulture); }
        }
        public static string Rebase_Status_Pending {
            get { return ResourceManager.GetString("Rebase_Status_Pending", resourceCulture); }
        }
        public static string Rebase_Status_Copying {
            get { return ResourceManager.GetString("Rebase_Status_Copying", resourceCulture); }
        }
        public static string Rebase_Status_Done {
            get { return ResourceManager.GetString("Rebase_Status_Done", resourceCulture); }
        }
        public static string Rebase_Status_Skipped {
            get { return ResourceManager.GetString("Rebase_Status_Skipped", resourceCulture); }
        }
        public static string Rebase_Status_Failed {
            get { return ResourceManager.GetString("Rebase_Status_Failed", resourceCulture); }
        }
        public static string Rebase_Validation_NoTarget {
            get { return ResourceManager.GetString("Rebase_Validation_NoTarget", resourceCulture); }
        }
        public static string Rebase_Validation_NoArchitecture {
            get { return ResourceManager.GetString("Rebase_Validation_NoArchitecture", resourceCulture); }
        }
        public static string Rebase_Validation_NoGames {
            get { return ResourceManager.GetString("Rebase_Validation_NoGames", resourceCulture); }
        }
        public static string Rebase_Validation_UnmappedSystems {
            get { return ResourceManager.GetString("Rebase_Validation_UnmappedSystems", resourceCulture); }
        }
        public static string Rebase_Validation_NoSpace {
            get { return ResourceManager.GetString("Rebase_Validation_NoSpace", resourceCulture); }
        }
        public static string Rebase_Completed {
            get { return ResourceManager.GetString("Rebase_Completed", resourceCulture); }
        }
        public static string Rebase_Column_Status {
            get { return ResourceManager.GetString("Rebase_Column_Status", resourceCulture); }
        }
        public static string Rebase_Column_Title {
            get { return ResourceManager.GetString("Rebase_Column_Title", resourceCulture); }
        }
        public static string Rebase_Column_System {
            get { return ResourceManager.GetString("Rebase_Column_System", resourceCulture); }
        }
        public static string Rebase_Column_Files {
            get { return ResourceManager.GetString("Rebase_Column_Files", resourceCulture); }
        }
        public static string Rebase_Column_Progress {
            get { return ResourceManager.GetString("Rebase_Column_Progress", resourceCulture); }
        }
        public static string Rebase_Column_Error {
            get { return ResourceManager.GetString("Rebase_Column_Error", resourceCulture); }
        }
        public static string Rebase_GamesCount {
            get { return ResourceManager.GetString("Rebase_GamesCount", resourceCulture); }
        }
        public static string Rebase_Speed {
            get { return ResourceManager.GetString("Rebase_Speed", resourceCulture); }
        }
        public static string Rebase_ETA {
            get { return ResourceManager.GetString("Rebase_ETA", resourceCulture); }
        }
        public static string Rebase_Ready {
            get { return ResourceManager.GetString("Rebase_Ready", resourceCulture); }
        }
        public static string Status_Pending {
            get { return ResourceManager.GetString("Status_Pending", resourceCulture); }
        }
        public static string Rebase_CloseTitle {
            get { return ResourceManager.GetString("Rebase_CloseTitle", resourceCulture); }
        }
        public static string Rebase_CloseMessage {
            get { return ResourceManager.GetString("Rebase_CloseMessage", resourceCulture); }
        }
        public static string Rebase_CloseConfirm {
            get { return ResourceManager.GetString("Rebase_CloseConfirm", resourceCulture); }
        }
        public static string General_Cancel {
            get { return ResourceManager.GetString("General_Cancel", resourceCulture); }
        }
        public static string General_Yes {
            get { return ResourceManager.GetString("General_Yes", resourceCulture); }
        }
        public static string Rebase_FolderNotExist {
            get { return ResourceManager.GetString("Rebase_FolderNotExist", resourceCulture); }
        }
        public static string Rebase_FolderCreate {
            get { return ResourceManager.GetString("Rebase_FolderCreate", resourceCulture); }
        }
        public static string Rebase_FolderNotEmpty {
            get { return ResourceManager.GetString("Rebase_FolderNotEmpty", resourceCulture); }
        }
        public static string Rebase_CancelCalcTitle {
            get { return ResourceManager.GetString("Rebase_CancelCalcTitle", resourceCulture); }
        }
        public static string Rebase_CancelCalcMessage {
            get { return ResourceManager.GetString("Rebase_CancelCalcMessage", resourceCulture); }
        }
        public static string Rebase_CalculationCancelled {
            get { return ResourceManager.GetString("Rebase_CalculationCancelled", resourceCulture); }
        }
        public static string Rebase_RetryAttempts {
            get { return ResourceManager.GetString("Rebase_RetryAttempts", resourceCulture); }
        }
        public static string Rebase_RetryDelay {
            get { return ResourceManager.GetString("Rebase_RetryDelay", resourceCulture); }
        }
        public static string Rebase_RetryDelayUnit {
            get { return ResourceManager.GetString("Rebase_RetryDelayUnit", resourceCulture); }
        }
        public static string Rebase_Cancelling {
            get { return ResourceManager.GetString("Rebase_Cancelling", resourceCulture); }
        }
        public static string Rebase_Completed_Title {
            get { return ResourceManager.GetString("Rebase_Completed_Title", resourceCulture); }
        }
        public static string Rebase_Completed_Success {
            get { return ResourceManager.GetString("Rebase_Completed_Success", resourceCulture); }
        }
        public static string Rebase_Completed_Partial_Title {
            get { return ResourceManager.GetString("Rebase_Completed_Partial_Title", resourceCulture); }
        }
        public static string Rebase_Completed_Partial {
            get { return ResourceManager.GetString("Rebase_Completed_Partial", resourceCulture); }
        }
        public static string Rebase_Error_Title {
            get { return ResourceManager.GetString("Rebase_Error_Title", resourceCulture); }
        }
        public static string Rebase_Error_Message {
            get { return ResourceManager.GetString("Rebase_Error_Message", resourceCulture); }
        }
        public static string Rebase_Error_DirectoryNotFound {
            get { return ResourceManager.GetString("Rebase_Error_DirectoryNotFound", resourceCulture); }
        }
        public static string Rebase_Error_AccessDenied {
            get { return ResourceManager.GetString("Rebase_Error_AccessDenied", resourceCulture); }
        }
        public static string Rebase_Error_DiskFull {
            get { return ResourceManager.GetString("Rebase_Error_DiskFull", resourceCulture); }
        }
        public static string Rebase_Error_Interrupted {
            get { return ResourceManager.GetString("Rebase_Error_Interrupted", resourceCulture); }
        }
        public static string Sync_InProgress {
            get { return ResourceManager.GetString("Sync_InProgress", resourceCulture); }
        }
        public static string Sync_ErrorTitle {
            get { return ResourceManager.GetString("Sync_ErrorTitle", resourceCulture); }
        }
        public static string Settings_Title {
            get { return ResourceManager.GetString("Settings_Title", resourceCulture); }
        }
        public static string Settings_Section_General {
            get { return ResourceManager.GetString("Settings_Section_General", resourceCulture); }
        }
        public static string Settings_Section_Display {
            get { return ResourceManager.GetString("Settings_Section_Display", resourceCulture); }
        }
        public static string Settings_Language {
            get { return ResourceManager.GetString("Settings_Language", resourceCulture); }
        }
        public static string Settings_Language_Auto {
            get { return ResourceManager.GetString("Settings_Language_Auto", resourceCulture); }
        }
        public static string Settings_Language_Fr {
            get { return ResourceManager.GetString("Settings_Language_Fr", resourceCulture); }
        }
        public static string Settings_Language_En {
            get { return ResourceManager.GetString("Settings_Language_En", resourceCulture); }
        }
        public static string Settings_Theme {
            get { return ResourceManager.GetString("Settings_Theme", resourceCulture); }
        }
        public static string Settings_Theme_Light {
            get { return ResourceManager.GetString("Settings_Theme_Light", resourceCulture); }
        }
        public static string Settings_Theme_Dark {
            get { return ResourceManager.GetString("Settings_Theme_Dark", resourceCulture); }
        }
        public static string Settings_RestartRequired {
            get { return ResourceManager.GetString("Settings_RestartRequired", resourceCulture); }
        }
        public static string Settings_Save {
            get { return ResourceManager.GetString("Settings_Save", resourceCulture); }
        }
        public static string Settings_Cancel {
            get { return ResourceManager.GetString("Settings_Cancel", resourceCulture); }
        }
        public static string Settings_Section_Locations {
            get { return ResourceManager.GetString("Settings_Section_Locations", resourceCulture); }
        }
        public static string Settings_OpenInstallFolder {
            get { return ResourceManager.GetString("Settings_OpenInstallFolder", resourceCulture); }
        }
        public static string Settings_OpenUserDataFolder {
            get { return ResourceManager.GetString("Settings_OpenUserDataFolder", resourceCulture); }
        }
        public static string Settings_OpenRomStationFolder {
            get { return ResourceManager.GetString("Settings_OpenRomStationFolder", resourceCulture); }
        }
        public static string Rebase_Error_InvalidDriveLetter {
            get { return ResourceManager.GetString("Rebase_Error_InvalidDriveLetter", resourceCulture); }
        }
        public static string Rebase_Error_FolderNotExist {
            get { return ResourceManager.GetString("Rebase_Error_FolderNotExist", resourceCulture); }
        }
        public static string Rebase_Validation_PathNotAbsolute {
            get { return ResourceManager.GetString("Rebase_Validation_PathNotAbsolute", resourceCulture); }
        }
        public static string Splash_RSNotFound_Title {
            get { return ResourceManager.GetString("Splash_RSNotFound_Title", resourceCulture); }
        }
        public static string Splash_RSNotFound_Message {
            get { return ResourceManager.GetString("Splash_RSNotFound_Message", resourceCulture); }
        }
        public static string Splash_RSNotFound_Browse {
            get { return ResourceManager.GetString("Splash_RSNotFound_Browse", resourceCulture); }
        }
        public static string Splash_RSNotFound_Quit {
            get { return ResourceManager.GetString("Splash_RSNotFound_Quit", resourceCulture); }
        }
        public static string Splash_RSNotFound_InvalidFolder {
            get { return ResourceManager.GetString("Splash_RSNotFound_InvalidFolder", resourceCulture); }
        }
        public static string Splash_RSNotFound_SelectFolder {
            get { return ResourceManager.GetString("Splash_RSNotFound_SelectFolder", resourceCulture); }
        }
        public static string Splash_RSNotFound_StepFailed {
            get { return ResourceManager.GetString("Splash_RSNotFound_StepFailed", resourceCulture); }
        }
        public static string Settings_Section_About {
            get { return ResourceManager.GetString("Settings_Section_About", resourceCulture); }
        }
        public static string Settings_About_Copyright {
            get { return ResourceManager.GetString("Settings_About_Copyright", resourceCulture); }
        }
        public static string Settings_About_OpenRepository {
            get { return ResourceManager.GetString("Settings_About_OpenRepository", resourceCulture); }
        }

        public static string Splash_DBNotInitialized_Title {
            get { return ResourceManager.GetString("Splash_DBNotInitialized_Title", resourceCulture); }
        }

        public static string Splash_DBNotInitialized_Message {
            get { return ResourceManager.GetString("Splash_DBNotInitialized_Message", resourceCulture); }
        }

        public static string Splash_DBNotInitialized_StepLabel {
            get { return ResourceManager.GetString("Splash_DBNotInitialized_StepLabel", resourceCulture); }
        }

        public static string Splash_DBNotInitialized_Quit {
            get { return ResourceManager.GetString("Splash_DBNotInitialized_Quit", resourceCulture); }
        }

        public static string Splash_DBCorrupted_Title {
            get { return ResourceManager.GetString("Splash_DBCorrupted_Title", resourceCulture); }
        }

        public static string Splash_UnexpectedError_Title {
            get { return ResourceManager.GetString("Splash_UnexpectedError_Title", resourceCulture); }
        }

        public static string Splash_UnexpectedError_Message {
            get { return ResourceManager.GetString("Splash_UnexpectedError_Message", resourceCulture); }
        }

        public static string Splash_UnexpectedError_Quit {
            get { return ResourceManager.GetString("Splash_UnexpectedError_Quit", resourceCulture); }
        }

        public static string Main_SizeNormal {
            get { return ResourceManager.GetString("Main_SizeNormal", resourceCulture); }
        }

        public static string Main_SizeLarge {
            get { return ResourceManager.GetString("Main_SizeLarge", resourceCulture); }
        }

        public static string Main_ThumbnailSize_Tooltip {
            get { return ResourceManager.GetString("Main_ThumbnailSize_Tooltip", resourceCulture); }
        }

        public static string Main_ThumbnailSize_Label {
            get { return ResourceManager.GetString("Main_ThumbnailSize_Label", resourceCulture); }
        }

        public static string Main_SortBy_Label {
            get { return ResourceManager.GetString("Main_SortBy_Label", resourceCulture); }
        }

        public static string Main_SortBy_Title {
            get { return ResourceManager.GetString("Main_SortBy_Title", resourceCulture); }
        }

        public static string Main_SortBy_System {
            get { return ResourceManager.GetString("Main_SortBy_System", resourceCulture); }
        }

        public static string Sync_Confirm_Title {
            get { return ResourceManager.GetString("Sync_Confirm_Title", resourceCulture); }
        }

        public static string Sync_Confirm_Message {
            get { return ResourceManager.GetString("Sync_Confirm_Message", resourceCulture); }
        }

        public static string Sync_Confirm_MessageWithSelection {
            get { return ResourceManager.GetString("Sync_Confirm_MessageWithSelection", resourceCulture); }
        }

        public static string Sync_Confirm_Singular {
            get { return ResourceManager.GetString("Sync_Confirm_Singular", resourceCulture); }
        }

        public static string Sync_Confirm_Plural {
            get { return ResourceManager.GetString("Sync_Confirm_Plural", resourceCulture); }
        }

        public static string Sync_Confirm_Proceed {
            get { return ResourceManager.GetString("Sync_Confirm_Proceed", resourceCulture); }
        }

        public static string Sync_Confirm_Cancel {
            get { return ResourceManager.GetString("Sync_Confirm_Cancel", resourceCulture); }
        }

        public static string GameDetail_Title {
            get { return ResourceManager.GetString("GameDetail_Title", resourceCulture); }
        }

        public static string GameDetail_Close {
            get { return ResourceManager.GetString("GameDetail_Close", resourceCulture); }
        }
    }
}
